/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-06-15 15:33:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.green.beans.Member;

public final class Ex_005f03_005fResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.green.beans.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>자바빈과 액션 태그</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		request.setCharacterEncoding("UTF-8");
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("			");

				Member m1 = new Member();
				session.setAttribute("m1", m1);
			
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("			");
      com.green.beans.Member m2 = null;
      synchronized (session) {
        m2 = (com.green.beans.Member) _jspx_page_context.getAttribute("m2", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (m2 == null){
          m2 = new com.green.beans.Member();
          _jspx_page_context.setAttribute("m2", m2, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("			\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("			");

				String name = request.getParameter("name");
				String userId = request.getParameter("userId");
				String nickname = request.getParameter("nickname");
				String userPw = request.getParameter("userPw");
				String email = request.getParameter("email");
				String phone = request.getParameter("phone");
				m1.setName(name);
				m1.setUserId(userId);
				m1.setNickname(nickname);
				m1.setUserPw(userPw);
				m1.setEmail(email);
				m1.setPhone(phone);
			
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("			");

				m2.setName(request.getParameter("name"));
				m2.setUserId(request.getParameter("userId"));
				m2.setNickname(request.getParameter("nickname"));
				m2.setUserPw(request.getParameter("userPw"));
				m2.setEmail(request.getParameter("email"));
				m2.setPhone(request.getParameter("phone"));
			
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("m1"), "name",
request.getParameter("name"));
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("m1"), "userId",
request.getParameter("userId"));
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("m1"), "nickname",
request.getParameter("nickname"));
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("m1"), "userPw",
request.getParameter("userPw"));
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("m1"), "email",
request.getParameter("email"));
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("m1"), "phone",
request.getParameter("phone"));
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("m2"), "name", request.getParameter("name"), request, "name", false);
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("m2"), "userId", request.getParameter("userId"), request, "userId", false);
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("m2"), "nickname", request.getParameter("nickname"), request, "nickname", false);
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("m2"), "userPw", request.getParameter("userPw"), request, "userPw", false);
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("m2"), "email", request.getParameter("email"), request, "email", false);
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("m2"), "phone", request.getParameter("phone"), request, "phone", false);
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("m2"), request);
      out.write("\r\n");
      out.write("			\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("		<h1>입력된 회원 정보 출력</h1>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("			이름 : ");
      out.print(m1.getName());
      out.write("<br>\r\n");
      out.write("			닉네임 : ");
      out.print(m1.getNickname());
      out.write("<br>\r\n");
      out.write("			아이디 : ");
      out.print(m1.getUserId());
      out.write("<br>\r\n");
      out.write("			비밀번호 : ");
      out.print(m1.getUserPw());
      out.write("<br>\r\n");
      out.write("			이메일 : ");
      out.print(m1.getEmail());
      out.write("<br>\r\n");
      out.write("			전화번호 : ");
      out.print(m1.getPhone());
      out.write("<hr>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("			이름 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.green.beans.Member)_jspx_page_context.findAttribute("m2")).getName())));
      out.write("<br>\r\n");
      out.write("			닉네임 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.green.beans.Member)_jspx_page_context.findAttribute("m2")).getNickname())));
      out.write("<br>\r\n");
      out.write("			아이디 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.green.beans.Member)_jspx_page_context.findAttribute("m2")).getUserId())));
      out.write("<br>\r\n");
      out.write("			비밀번호 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.green.beans.Member)_jspx_page_context.findAttribute("m2")).getUserPw())));
      out.write("<br>\r\n");
      out.write("			이메일 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.green.beans.Member)_jspx_page_context.findAttribute("m2")).getEmail())));
      out.write("<br>\r\n");
      out.write("			전화번호 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.green.beans.Member)_jspx_page_context.findAttribute("m2")).getPhone())));
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
